### ISSUE TITLE
library does not check current state

### ISSUE THREAD

**Issue by ggrillone** [karl/redux-wait-for-state#1]
For some use cases - it is a bug that the state is not checked immediately. Looking at the code the promise will only ever be resolved when the store changes.

Take for example routing - I want to make sure the current user object is loaded in the store before transitioning. If the user is already loaded and I click a nav button to go to a different page - the promise never resolves since the user object already exists.

**Comment by karl** [comment]
Hi @ggrillone, thanks for the bug report. I'd messed up my GitHub notifications, so only just spotted this!

I'll try and look into this next week, and see if I can get it to test the state immediately (unless you want to attempt a PR yourself).

**Comment by karl** [comment]
@ggrillone I have a PR to check for the state immediately (#2).

Would you be in a position to test whether this fixes the problem you are seeing?

If so I'm happy to publish a new version on npm to get this released.

**Comment by karl** [comment]
Fixed by #2 and released as `2.0.0` on npm.
